default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: postgres
  password: secret

development:
  <<: *default
  database: ror_app
  username: postgres
  password: secret

test:
  <<: *default
  database: ror_app_test

production:
  <<: *default
  database: ror_app
